import { PrismaClient } from "../generated/client";

const prisma = new PrismaClient();

const nepalGeo = {
  provinces: [
    { name: "Koshi", nameNp: "कोशी प्रदेश" },
    { name: "Madhesh", nameNp: "मधेश प्रदेश" },
    { name: "Bagmati", nameNp: "बाग्मती प्रदेश" },
    { name: "Gandaki", nameNp: "गण्डकी प्रदेश" },
    { name: "Lumbini", nameNp: "लुम्बिनी प्रदेश" },
    { name: "Karnali", nameNp: "कर्णाली प्रदेश" },
    { name: "Sudurpashchim", nameNp: "सुदूरपश्चिम प्रदेश" },
  ],
  districts: [
    { name: "Bhotgairi", nameNp: "भोटगैरी", province: "Koshi" },
    { name: "Dhankuta", nameNp: "धनकुटा", province: "Koshi" },
    { name: "Ilam", nameNp: "इलाम", province: "Koshi" },
    { name: "Jhapa", nameNp: "झापा", province: "Koshi" },
    { name: "Khotang", nameNp: "खोटाङ", province: "Koshi" },
    { name: "Morang", nameNp: "मोरङ", province: "Koshi" },
    { name: "Okhaldhunga", nameNp: "ओखलढुङ्गा", province: "Koshi" },
    { name: "Panchthar", nameNp: "पाँचथर", province: "Koshi" },
    { name: "Sankhuwasabha", nameNp: "संखुवासभा", province: "Koshi" },
    { name: "Solukhumbu", nameNp: "सोलुखुम्बु", province: "Koshi" },
    { name: "Sunsari", nameNp: "सुनसरी", province: "Koshi" },
    { name: "Taplejung", nameNp: "ताप्लेजुङ", province: "Koshi" },
    { name: "Terhathum", nameNp: "तेह्रथुम", province: "Koshi" },
    { name: "Udayapur", nameNp: "उदयपुर", province: "Koshi" },
    { name: "Bara", nameNp: "बारा", province: "Madhesh" },
    { name: "Dhanusa", nameNp: "धनुषा", province: "Madhesh" },
    { name: "Mahottari", nameNp: "महोत्तरी", province: "Madhesh" },
    { name: "Parsa", nameNp: "पर्सा", province: "Madhesh" },
    { name: "Rautahat", nameNp: "रौतहट", province: "Madhesh" },
    { name: "Sarlahi", nameNp: "सर्लाही", province: "Madhesh" },
    { name: "Saptari", nameNp: "सप्तरी", province: "Madhesh" },
    { name: "Siraha", nameNp: "सिराहा", province: "Madhesh" },
    { name: "Bhaktapur", nameNp: "भक्तपुर", province: "Bagmati" },
    { name: "Chitwan", nameNp: "चितवन", province: "Bagmati" },
    { name: "Dhading", nameNp: "धादिङ", province: "Bagmati" },
    { name: "Kathmandu", nameNp: "काठमाडौं", province: "Bagmati" },
    { name: "Kavrepalanchok", nameNp: "काभ्रेपलान्चोक", province: "Bagmati" },
    { name: "Lalitpur", nameNp: "ललितपुर", province: "Bagmati" },
    { name: "Makwanpur", nameNp: "मकवानपुर", province: "Bagmati" },
    { name: "Nuwakot", nameNp: "नुवाकोट", province: "Bagmati" },
    { name: "Ramechhap", nameNp: "रामेछाप", province: "Bagmati" },
    { name: "Rasuwa", nameNp: "रसुवा", province: "Bagmati" },
    { name: "Sindhuli", nameNp: "सिन्धुली", province: "Bagmati" },
    { name: "Sindhupalchok", nameNp: "सिन्धुपाल्चोक", province: "Bagmati" },
    { name: "Dolakha", nameNp: "दोलखा", province: "Bagmati" },
    { name: "Baglung", nameNp: "बाग्लुङ", province: "Gandaki" },
    { name: "Gorkha", nameNp: "गोरखा", province: "Gandaki" },
    { name: "Kaski", nameNp: "कास्की", province: "Gandaki" },
    { name: "Lamjung", nameNp: "लमजुङ", province: "Gandaki" },
    { name: "Manang", nameNp: "मनाङ", province: "Gandaki" },
    { name: "Mustang", nameNp: "मुस्ताङ", province: "Gandaki" },
    { name: "Myagdi", nameNp: "म्याग्दी", province: "Gandaki" },
    { name: "Nawalparasi East", nameNp: "नवलपरासी पूर्व", province: "Gandaki" },
    {
      name: "Nawalparasi West",
      nameNp: "नवलपरासी पश्चिम",
      province: "Gandaki",
    },
    { name: "Parbat", nameNp: "पर्वत", province: "Gandaki" },
    { name: "Syangja", nameNp: "स्याङ्जा", province: "Gandaki" },
    { name: "Tanahun", nameNp: "तनहुँ", province: "Gandaki" },
    { name: "Arghakhanchi", nameNp: "अर्घाखाँची", province: "Lumbini" },
    { name: "Banke", nameNp: "बाँके", province: "Lumbini" },
    { name: "Bardiya", nameNp: "बर्दिया", province: "Lumbini" },
    { name: "Butwal", nameNp: "बुटवल", province: "Lumbini" },
    { name: "Dang", nameNp: "दाङ", province: "Lumbini" },
    { name: "East Rukum", nameNp: "पूर्वी रुकुम", province: "Lumbini" },
    { name: "Gulmi", nameNp: "गुल्मी", province: "Lumbini" },
    { name: "Kapilvastu", nameNp: "कपिलवस्तु", province: "Lumbini" },
    { name: "Nawalparasi", nameNp: "नवलपरासी", province: "Lumbini" },
    { name: "Palpa", nameNp: "पाल्पा", province: "Lumbini" },
    { name: "Pyuthan", nameNp: "प्यूठान", province: "Lumbini" },
    { name: "Rupandehi", nameNp: "रुपन्देही", province: "Lumbini" },
    { name: "Dailekh", nameNp: "दैलेख", province: "Karnali" },
    { name: "Dolpa", nameNp: "डोल्पा", province: "Karnali" },
    { name: "Jajarkot", nameNp: "जाजरकोट", province: "Karnali" },
    { name: "Jumla", nameNp: "जुम्ला", province: "Karnali" },
    { name: "Kalikot", nameNp: "कालिकोट", province: "Karnali" },
    { name: "Mugu", nameNp: "मुगु", province: "Karnali" },
    { name: "Salyan", nameNp: "सल्यान", province: "Karnali" },
    { name: "Surkhet", nameNp: "सुर्खेत", province: "Karnali" },
    { name: "West Rukum", nameNp: "पश्चिमी रुकुम", province: "Karnali" },
    { name: "Humla", nameNp: "हुम्ला", province: "Karnali" },
    { name: "Achham", nameNp: "अछाम", province: "Sudurpashchim" },
    { name: "Baitadi", nameNp: "बैतडी", province: "Sudurpashchim" },
    { name: "Bajhang", nameNp: "बझाङ", province: "Sudurpashchim" },
    { name: "Bajura", nameNp: "बाजुरा", province: "Sudurpashchim" },
    { name: "Dadeldhura", nameNp: "डडेल्धुरा", province: "Sudurpashchim" },
    { name: "Darchula", nameNp: "दार्चुला", province: "Sudurpashchim" },
    { name: "Doti", nameNp: "डोटी", province: "Sudurpashchim" },
    { name: "Kailali", nameNp: "कैलाली", province: "Sudurpashchim" },
    { name: "Kanchanpur", nameNp: "कञ्चनपुर", province: "Sudurpashchim" },
  ],
  municipalities: {
    Bhotgairi: [
      { name: "Bhotgairi", nameNp: "भोटगैरी", type: "Rural Municipality" },
    ],
    Dhankuta: [
      {
        name: "Dhankuta Municipality",
        nameNp: "धनकुटा नगरपालिका",
        type: "Municipality",
      },
      { name: "Pakhribas", nameNp: "पख्रिबास", type: "Municipality" },
      { name: "Mahalaxmi", nameNp: "महालक्ष्मी", type: "Municipality" },
      { name: "Sangurigadi", nameNp: "सगरुनियाँ", type: "Rural Municipality" },
      { name: "Chhathar", nameNp: "छथर", type: "Rural Municipality" },
    ],
    Ilam: [
      {
        name: "Ilam Municipality",
        nameNp: "इलाम नगरपालिका",
        type: "Municipality",
      },
      { name: "Deumai", nameNp: "देउमाई", type: "Municipality" },
      { name: "Mai", nameNp: "माई", type: "Municipality" },
      { name: "Suryodaya", nameNp: "सूर्योदय", type: "Municipality" },
      { name: "Phakphokthum", nameNp: "फाकफोकथुम", type: "Rural Municipality" },
      { name: "Rong", nameNp: "रोङ", type: "Rural Municipality" },
    ],
    Jhapa: [
      { name: "Bhadrapur", nameNp: "भद्रपुर", type: "Municipality" },
      { name: "Birtamod", nameNp: "विर्तामोड", type: "Municipality" },
      { name: "Damak", nameNp: "दमक", type: "Municipality" },
      { name: "Ithari", nameNp: "इटहरी", type: "Municipality" },
      { name: "Kankai", nameNp: "कनकाई", type: "Municipality" },
      { name: "Mechinagar", nameNp: "मेचीनगर", type: "Municipality" },
      { name: "Arjundhara", nameNp: "अर्जुनधारा", type: "Municipality" },
      { name: "Gauradaha", nameNp: "गौरादह", type: "Municipality" },
      { name: "Kamal", nameNp: "कमल", type: "Rural Municipality" },
      { name: "Shivasatasi", nameNp: "शिवसतासी", type: "Municipality" },
      { name: "Jhapa", nameNp: "झापा", type: "Rural Municipality" },
      {
        name: "Buddhashanti",
        nameNp: "बुद्धशान्ति",
        type: "Rural Municipality",
      },
    ],
    Khotang: [
      {
        name: "Halesi Tuwachung",
        nameNp: "हलेसी तुवाचुङ",
        type: "Municipality",
      },
      { name: "Khotang Bazar", nameNp: "खोटाङ बजार", type: "Municipality" },
      {
        name: "Diktel Rupakot",
        nameNp: "दिक्तेल रुपाकोट",
        type: "Municipality",
      },
      { name: "Aiselukharka", nameNp: "ऐसेलुखर्क", type: "Rural Municipality" },
      { name: "Lamidanda", nameNp: "लामिडान्डा", type: "Rural Municipality" },
    ],
    Morang: [
      { name: "Biratnagar", nameNp: "विराटनगर", type: "Metropolitan City" },
      { name: "Biratchowk", nameNp: "विर्ता चोक", type: "Municipality" },
      { name: "Sundar Dulari", nameNp: "सुनदुलरी", type: "Municipality" },
      { name: "Belbari", nameNp: "बेलबारी", type: "Municipality" },
      { name: "Letang", nameNp: "लेटाङ", type: "Municipality" },
      { name: "Mongla", nameNp: "मोङ्ला", type: "Municipality" },
      {
        name: "Pathari Sanischare",
        nameNp: "पाथरी सानीसचौर",
        type: "Municipality",
      },
      { name: "Rangeli", nameNp: "रंगेली", type: "Municipality" },
      { name: "Sunauli", nameNp: "सुनौली", type: "Municipality" },
      { name: "Jahada", nameNp: "जहदा", type: "Rural Municipality" },
      { name: "Miklajung", nameNp: "मिक्लाजुङ", type: "Rural Municipality" },
    ],
    Okhaldhunga: [
      { name: "Siddhicharan", nameNp: "सिद्धिचरण", type: "Municipality" },
      { name: "Champadevi", nameNp: "चम्पादेवी", type: "Rural Municipality" },
      { name: "Likhu", nameNp: "लिखु", type: "Rural Municipality" },
      { name: "Molung", nameNp: "मोलुङ", type: "Rural Municipality" },
    ],
    Panchthar: [
      { name: "Phidim", nameNp: "फिदिम", type: "Municipality" },
      { name: "Falelung", nameNp: "फालेलुङ", type: "Rural Municipality" },
      { name: "Hilihang", nameNp: "हिलिहाङ", type: "Rural Municipality" },
      { name: "Kummayak", nameNp: "कुम्मायक", type: "Rural Municipality" },
      { name: "Tumbweba", nameNp: "तुम्वेबा", type: "Rural Municipality" },
    ],
    Sankhuwasabha: [
      { name: "Khandbari", nameNp: "खाँडबराल", type: "Municipality" },
      { name: "Madi", nameNp: "माडी", type: "Municipality" },
      { name: "Dharmadevi", nameNp: "धर्मादेवी", type: "Municipality" },
      { name: "Bhotgairi", nameNp: "भोटगैरी", type: "Rural Municipality" },
      { name: "Makalu", nameNp: "मकालु", type: "Rural Municipality" },
    ],
    Solukhumbu: [
      { name: "Salleri", nameNp: "सल्लेरी", type: "Municipality" },
      { name: "Dudhkunda", nameNp: "दुध्कुण्ड", type: "Municipality" },
      {
        name: "Khumbupasang Lhamu",
        nameNp: "खुम्बुपासाङल्हामु",
        type: "Rural Municipality",
      },
      { name: "Nechasalyan", nameNp: "नेचासल्यान", type: "Rural Municipality" },
    ],
    Sunsari: [
      { name: "Inaruwa", nameNp: "इनरुवा", type: "Sub-Metropolitan City" },
      { name: "Itahari", nameNp: "इटहरी", type: "Sub-Metropolitan City" },
      { name: "Dharan", nameNp: "धरान", type: "Sub-Metropolitan City" },
      { name: "Duhabi", nameNp: "दुहबी", type: "Municipality" },
      { name: "Gadhi", nameNp: "गढी", type: "Municipality" },
      { name: "Ramdhuni", nameNp: "रामधुनी", type: "Municipality" },
      { name: "Baraha", nameNp: "बराह", type: "Municipality" },
      { name: "Bhokraha", nameNp: "भोक्राहा", type: "Rural Municipality" },
    ],
    Taplejung: [
      { name: "Phungling", nameNp: "फुङलिङ", type: "Municipality" },
      { name: "Meringden", nameNp: "मेरिङदेन", type: "Municipality" },
      {
        name: "Aathrai Tribeni",
        nameNp: "आथारी त्रिबेणी",
        type: "Rural Municipality",
      },
      { name: "Mikwakhola", nameNp: "मिक्वाकोला", type: "Rural Municipality" },
      { name: "Sidingwa", nameNp: "सिडिङवा", type: "Rural Municipality" },
    ],
    Terhathum: [
      { name: "Myanglung", nameNp: "म्याङलुङ", type: "Municipality" },
      { name: "Lokendra", nameNp: "लोकेन्रा", type: "Municipality" },
      { name: "Aathrai", nameNp: "आथारी", type: "Rural Municipality" },
      { name: "Chhathar", nameNp: "छथर", type: "Rural Municipality" },
    ],
    Udayapur: [
      { name: "Triyuga", nameNp: "त्रियुगा", type: "Municipality" },
      { name: "Katari", nameNp: "कटारी", type: "Municipality" },
      {
        name: "Udayapurgadhi",
        nameNp: "उदयपुरगढी",
        type: "Rural Municipality",
      },
      { name: "Rupachandi", nameNp: "रुपाचण्डी", type: "Rural Municipality" },
    ],
    Bara: [
      { name: "Kalaiya", nameNp: "कलैया", type: "Sub-Metropolitan City" },
      { name: "Bara", nameNp: "बारा", type: "Municipality" },
      { name: "Gaur", nameNp: "गौर", type: "Municipality" },
      { name: "Jeetpur", nameNp: "जीतपुर", type: "Municipality" },
      { name: "Karaiyamai", nameNp: "करैयामाई", type: "Municipality" },
      { name: "Mahagadhimai", nameNp: "महागढीमाई", type: "Municipality" },
      { name: "Nijgadh", nameNp: "निजगढ", type: "Municipality" },
      { name: "Pacharauta", nameNp: "पचरौता", type: "Municipality" },
      { name: "Parwanipur", nameNp: "परवानीपुर", type: "Municipality" },
      { name: "Prasauni", nameNp: "प्रसौनी", type: "Rural Municipality" },
      { name: "Simroungadh", nameNp: "शिमलौनी", type: "Municipality" },
    ],
    Dhanusa: [
      { name: "Janakpur", nameNp: "जनकपुर", type: "Sub-Metropolitan City" },
      { name: "Bateshwor", nameNp: "बतेश्वर", type: "Municipality" },
      { name: "Chhireshwor", nameNp: "छिरीश्वर", type: "Municipality" },
      { name: "Dhanusadham", nameNp: "धनुराधाम", type: "Municipality" },
      { name: "Gaurishankar", nameNp: "गौरीशङ्कर", type: "Rural Municipality" },
      { name: "Ghilabir", nameNp: "घिंलाबिर", type: "Municipality" },
      { name: "Hanspur", nameNp: "हंसपुर", type: "Municipality" },
      { name: "Kamala", nameNp: "कमला", type: "Municipality" },
      { name: "Katinandan", nameNp: "कटिनन्दन", type: "Municipality" },
      { name: "Laxminiya", nameNp: "लक्ष्मिनिया", type: "Municipality" },
      { name: "Mithila", nameNp: "मिथिला", type: "Municipality" },
      { name: "Mithila Bihari", nameNp: "मिथिला बिहारी", type: "Municipality" },
      { name: "Nagrah", nameNp: "नगराहा", type: "Municipality" },
      {
        name: "Shree Narayanpur",
        nameNp: "श्री नारायणपुर",
        type: "Municipality",
      },
    ],
    Mahottari: [
      { name: "Jaleshwor", nameNp: "जलेश्वर", type: "Municipality" },
      { name: "Aurahi", nameNp: "औरही", type: "Municipality" },
      { name: "Balawa", nameNp: "बलवा", type: "Municipality" },
      { name: "Bhangaha", nameNp: "भंगाहा", type: "Municipality" },
      { name: "Ekdanra", nameNp: "एकडारा", type: "Rural Municipality" },
      { name: "Gaushala", nameNp: "गौशाला", type: "Municipality" },
      { name: "Loharpatti", nameNp: "लोहरपट्टी", type: "Municipality" },
      { name: "Mahottari", nameNp: "महोत्तरी", type: "Rural Municipality" },
      { name: "Matihani", nameNp: "मटिहानी", type: "Municipality" },
      { name: "Ramgopalpur", nameNp: "रामगोपालपुर", type: "Municipality" },
      { name: "Samsi", nameNp: "समशी", type: "Rural Municipality" },
    ],
    Parsa: [
      { name: "Birgunj", nameNp: "बिरगञ्ज", type: "Metropolitan City" },
      { name: "Bahudarmai", nameNp: "बहुदरमाई", type: "Municipality" },
      { name: "Chhipaharmai", nameNp: "छिपहरमाई", type: "Municipality" },
      { name: "Dhobini", nameNp: "ढोबिनी", type: "Municipality" },
      { name: "Jigatola", nameNp: "जिगटोला", type: "Rural Municipality" },
      { name: "Kalamaha", nameNp: "कलमाहा", type: "Rural Municipality" },
      { name: "Pokhariya", nameNp: "पोखरिया", type: "Municipality" },
      { name: "Prasurampur", nameNp: "प्रसूरपुर", type: "Rural Municipality" },
      { name: "Sakhuwa", nameNp: "सखुवा", type: "Municipality" },
      { name: "Thori", nameNp: "थोरी", type: "Rural Municipality" },
    ],
    Rautahat: [
      { name: "Gaur", nameNp: "गौर", type: "Municipality" },
      { name: "Baudhimatha", nameNp: "बौद्धिमाता", type: "Municipality" },
      { name: "Brababan", nameNp: "ब्राह्मणबास", type: "Rural Municipality" },
      { name: "Chandrapur", nameNp: "चन्द्रपुर", type: "Municipality" },
      { name: "Devtal", nameNp: "देवताल", type: "Rural Municipality" },
      {
        name: "Durga Bhagwati",
        nameNp: "दुर्गा भगवती",
        type: "Rural Municipality",
      },
      { name: "Gadhimai", nameNp: "गढिमाई", type: "Municipality" },
      { name: "Gujaar", nameNp: "गुजर", type: "Municipality" },
      { name: "Katahariya", nameNp: "कटहरिया", type: "Municipality" },
      { name: "Madhav", nameNp: "माधव", type: "Municipality" },
      { name: "Mahiwan", nameNp: "महावीर", type: "Rural Municipality" },
      { name: "Parohanya", nameNp: "परोहानिया", type: "Municipality" },
      { name: "Rajdevi", nameNp: "राजदेवी", type: "Municipality" },
      { name: "Rajpur", nameNp: "राजपुर", type: "Rural Municipality" },
      { name: "Sakhuwa", nameNp: "सखुवा", type: "Rural Municipality" },
    ],
    Sarlahi: [
      { name: "Malangawa", nameNp: "मलङ्गवा", type: "Municipality" },
      { name: "Bagdol", nameNp: "बागडोल", type: "Municipality" },
      { name: "Balara", nameNp: "बलारा", type: "Municipality" },
      { name: "Barahathawa", nameNp: "बरहथवा", type: "Municipality" },
      { name: "Bishnu", nameNp: "विष्णु", type: "Municipality" },
      { name: "Bramhapuri", nameNp: "ब्रह्मपुरी", type: "Rural Municipality" },
      { name: "Chakraghatta", nameNp: "चक्रघट्टा", type: "Rural Municipality" },
      { name: "Chandranagar", nameNp: "चन्द्रनगर", type: "Rural Municipality" },
      { name: "Dhanakaul", nameNp: "धनकोल", type: "Rural Municipality" },
      { name: "Godeta", nameNp: "गोदेता", type: "Rural Municipality" },
      { name: "Harion", nameNp: "हरियोन", type: "Rural Municipality" },
      { name: "Haripur", nameNp: "हरिपुर", type: "Municipality" },
      { name: "Hassanpur", nameNp: "हसनपुर", type: "Municipality" },
      { name: "Ishworpur", nameNp: "ईश्वरपुर", type: "Municipality" },
      { name: "Kabilasi", nameNp: "कविलासी", type: "Municipality" },
      { name: "Khoriya", nameNp: "खोरिया", type: "Rural Municipality" },
      { name: "Laksminiya", nameNp: "लक्ष्मिनिया", type: "Municipality" },
      { name: "Mahinathpur", nameNp: "महिनाथपुर", type: "Rural Municipality" },
      { name: "Parsa", nameNp: "पर्सा", type: "Rural Municipality" },
      { name: "Ramnagar", nameNp: "रामनगर", type: "Rural Municipality" },
    ],
    Saptari: [
      { name: "Rajbiraj", nameNp: "राजबिराज", type: "Municipality" },
      { name: "Balan", nameNp: "बालन", type: "Rural Municipality" },
      { name: "Bishnupur", nameNp: "विष्णुपुर", type: "Municipality" },
      {
        name: "Chhinnamasta",
        nameNp: "छिन्नमस्ता",
        type: "Rural Municipality",
      },
      { name: "Dakneshwori", nameNp: "दकनेश्वरी", type: "Municipality" },
      {
        name: "Hanumannagar",
        nameNp: "हनुमाननगर",
        type: "Municipality",
      },
      { name: "Kalyanpur", nameNp: "कल्याणपुर", type: "Municipality" },
      { name: "Kanchanrup", nameNp: "कञ्चनरुप", type: "Municipality" },
      { name: "Mahadeva", nameNp: "महादेवा", type: "Rural Municipality" },
      { name: "Rupani", nameNp: "रुपानी", type: "Rural Municipality" },
      { name: "Sambhunath", nameNp: "शम्भुनाथ", type: "Municipality" },
      { name: "Saptakoshi", nameNp: "सप्तकोशी", type: "Municipality" },
      { name: "Shripur", nameNp: "श्रीपुर", type: "Rural Municipality" },
      { name: "Surunga", nameNp: "सुरुङ्गा", type: "Municipality" },
      { name: "Tirhut", nameNp: "तिर्थ", type: "Municipality" },
    ],
    Siraha: [
      { name: "Siraha", nameNp: "सिराहा", type: "Municipality" },
      { name: "Arnama", nameNp: "अर्णा", type: "Rural Municipality" },
      { name: "Aurahi", nameNp: "औरही", type: "Municipality" },
      {
        name: "Bariyarpatti",
        nameNp: "बरियारपट्टी",
        type: "Rural Municipality",
      },
      { name: "Bhagawanpur", nameNp: "भगवानपुर", type: "Rural Municipality" },
      { name: "Bishnupur", nameNp: "विष्णुपुर", type: "Municipality" },
      { name: "Dhanagadi", nameNp: "धनगढी", type: "Municipality" },
      { name: "Golbazar", nameNp: "गोलबजार", type: "Municipality" },
      { name: "Kalyan", nameNp: "कल्याण", type: "Municipality" },
      { name: "Karjanha", nameNp: "करजाना", type: "Municipality" },
      { name: "Lahan", nameNp: "लहान", type: "Municipality" },
      { name: "Laxmipur", nameNp: "लक्ष्मीपुर", type: "Municipality" },
      { name: "Mirhat", nameNp: "मीरहट", type: "Rural Municipality" },
      { name: "Naraha", nameNp: "नरहा", type: "Rural Municipality" },
      { name: "Nawaraj", nameNp: "नवराज", type: "Rural Municipality" },
      {
        name: "Sakhuwanankar",
        nameNp: "सखुवानankar",
        type: "Rural Municipality",
      },
    ],
    Bhaktapur: [
      { name: "Bhaktapur", nameNp: "भक्तपुर", type: "Municipality" },
      { name: "Changunarayan", nameNp: "चाँगुनारायण", type: "Municipality" },
      { name: "Madhyapur Thimi", nameNp: "मध्यपुर थिमि", type: "Municipality" },
      { name: "Suryabinayak", nameNp: "सूर्यबिनायक", type: "Municipality" },
    ],
    Chitwan: [
      { name: "Bharatpur", nameNp: "भरतपुर", type: "Metropolitan City" },
      { name: "Ratnanagar", nameNp: "रत्ननगर", type: "Municipality" },
      { name: "Khairahani", nameNp: "खैरहानी", type: "Municipality" },
      { name: "Madi", nameNp: "माडी", type: "Municipality" },
      { name: "Ichchha", nameNp: "इच्छा", type: "Municipality" },
      { name: "Rapti", nameNp: "राप्ती", type: "Municipality" },
      { name: "Kalika", nameNp: "कालिका", type: "Municipality" },
      { name: "Meghauli", nameNp: "मेघौली", type: "Municipality" },
    ],
    Dhading: [
      { name: "Nilkantha", nameNp: "नीलकण्ठ", type: "Municipality" },
      { name: "Dhading", nameNp: "धादिङ", type: "Municipality" },
      { name: "Gajuri", nameNp: "गजुरी", type: "Rural Municipality" },
      { name: "Galchi", nameNp: "गल्छी", type: "Rural Municipality" },
      { name: "Thakre", nameNp: "थाक्रे", type: "Rural Municipality" },
      { name: "Khaniyabash", nameNp: "खनियाबास", type: "Rural Municipality" },
      { name: "Jwalamukhi", nameNp: "ज्वालामुखी", type: "Rural Municipality" },
      { name: "Siddhalek", nameNp: "सिद्धलेक", type: "Rural Municipality" },
      {
        name: "Benighat Rorang",
        nameNp: "बेनीघाट रोराङ",
        type: "Rural Municipality",
      },
      {
        name: "Rubi Valley",
        nameNp: "रुबी उपत्यका",
        type: "Rural Municipality",
      },
      { name: "Tadi", nameNp: "तादी", type: "Rural Municipality" },
    ],
    Kathmandu: [
      { name: "Kathmandu", nameNp: "काठमाडौं", type: "Metropolitan City" },
      {
        name: "Kageshwari Manohara",
        nameNp: "काष्ठमाडौं",
        type: "Municipality",
      },
      { name: "Nagarjun", nameNp: "नागार्जुन", type: "Municipality" },
      { name: "Shankharapur", nameNp: "शङ्करापुर", type: "Municipality" },
      { name: "Tarakeshwor", nameNp: "तारकेश्वर", type: "Municipality" },
      { name: "Budhanilkantha", nameNp: "बूढानीलकण्ठ", type: "Municipality" },
      { name: "Gokarneswor", nameNp: "गोकर्णेश्वर", type: "Municipality" },
      { name: "Chandragiri", nameNp: "चन्द्रागिरी", type: "Municipality" },
      { name: "Tokha", nameNp: "टोखा", type: "Municipality" },
      { name: "Kisan", nameNp: "किसान", type: "Municipality" },
      { name: "Tarkeshwor", nameNp: "तारकेश्वर", type: "Municipality" },
      { name: "Mahalaxmi", nameNp: "महालक्ष्मी", type: "Municipality" },
      { name: "Kirtipur", nameNp: "कीर्तिपुर", type: "Municipality" },
    ],
    Kavrepalanchok: [
      { name: "Dhulikhel", nameNp: "धुलिखेल", type: "Municipality" },
      { name: "Banepa", nameNp: "बनेपा", type: "Municipality" },
      { name: "Panchkhal", nameNp: "पाँचखाल", type: "Municipality" },
      {
        name: "Kavrepalanchok",
        nameNp: "काभ्रेपलान्चोक",
        type: "Municipality",
      },
      { name: "Mandandeupur", nameNp: "मण्डनदेउपुर", type: "Municipality" },
      { name: "Namobuddha", nameNp: "नमोबुद्ध", type: "Municipality" },
      {
        name: "Chaurideurali",
        nameNp: "चौरीदेउराली",
        type: "Rural Municipality",
      },
      { name: "Temal", nameNp: "टेमाल", type: "Rural Municipality" },
      { name: "Mahendranagar", nameNp: "महेन्द्रनगर", type: "Municipality" },
    ],
    Lalitpur: [
      { name: "Lalitpur", nameNp: "ललितपुर", type: "Sub-Metropolitan City" },
      { name: "Godawari", nameNp: "गोदावरी", type: "Municipality" },
      { name: "Bagmati", nameNp: "बाग्मती", type: "Municipality" },
      { name: "Konjyosom", nameNp: "कोन्ज्योसोम", type: "Rural Municipality" },
      { name: "Mahalaxmi", nameNp: "महालक्ष्मी", type: "Municipality" },
      { name: "Sangachowk", nameNp: "सनगचोक", type: "Rural Municipality" },
    ],
    Makwanpur: [
      { name: "Hetauda", nameNp: "हेटौंडा", type: "Sub-Metropolitan City" },
      { name: "Bhimfedi", nameNp: "भिमफेदी", type: "Municipality" },
      { name: "Makawanpur", nameNp: "मकवानपुर", type: "Municipality" },
      { name: "Kulekhani", nameNp: "कुलेखानी", type: "Municipality" },
      { name: "Bagmati", nameNp: "बाग्मती", type: "Municipality" },
      { name: "Raksirang", nameNp: "राक्सिराङ", type: "Rural Municipality" },
      { name: "Manahari", nameNp: "मनहरी", type: "Rural Municipality" },
      { name: "Maha Devi", nameNp: "महादेवी", type: "Rural Municipality" },
    ],
    Nuwakot: [
      { name: "Bidur", nameNp: "विदुर", type: "Municipality" },
      { name: "Nuwakot", nameNp: "नुवाकोट", type: "Municipality" },
      { name: "Kakani", nameNp: "काकानी", type: "Rural Municipality" },
      { name: "Kispang", nameNp: "किस्पाङ", type: "Rural Municipality" },
      { name: "Meghang", nameNp: "मेगाङ", type: "Rural Municipality" },
      { name: "Narchyang", nameNp: "नार्च्याङ", type: "Rural Municipality" },
      { name: "Panchakanya", nameNp: "पञ्चकन्या", type: "Rural Municipality" },
      { name: "Shivapuri", nameNp: "शिवपुरी", type: "Rural Municipality" },
      { name: "Suryagadhi", nameNp: "सूर्यागढी", type: "Rural Municipality" },
      { name: "Tadi", nameNp: "तादी", type: "Rural Municipality" },
      { name: "Likhu", nameNp: "लिखु", type: "Rural Municipality" },
    ],
    Ramechhap: [
      { name: "Manthali", nameNp: "मन्थली", type: "Municipality" },
      { name: "Ramechhap", nameNp: "रामेछाप", type: "Municipality" },
      { name: "Umakunda", nameNp: "उमाकुण्ड", type: "Rural Municipality" },
      { name: "Khandadevi", nameNp: "खान्देवी", type: "Rural Municipality" },
      { name: "Gokulganga", nameNp: "गोकुलगङ्गा", type: "Rural Municipality" },
      {
        name: "Likhu Tamakoshi",
        nameNp: "लिखु तामाकोशी",
        type: "Rural Municipality",
      },
      { name: "Chhyauri", nameNp: "छ्याउरी", type: "Rural Municipality" },
      { name: "Sunkoshi", nameNp: "सुनकोशी", type: "Rural Municipality" },
      { name: "Doramba", nameNp: "दोराम्बा", type: "Rural Municipality" },
    ],
    Rasuwa: [
      { name: "Dhunche", nameNp: "धुन्चे", type: "Municipality" },
      { name: "Gosaikunda", nameNp: "गोसाइकुण्ड", type: "Rural Municipality" },
      { name: "Naukunda", nameNp: "नौकुण्ड", type: "Rural Municipality" },
      { name: "Kalika", nameNp: "कालिका", type: "Rural Municipality" },
      { name: "Parbat", nameNp: "पर्वत", type: "Rural Municipality" },
    ],
    Sindhuli: [
      { name: "Kamalamai", nameNp: "कमलामाई", type: "Municipality" },
      { name: "Sindhuli", nameNp: "सिन्धुली", type: "Municipality" },
      { name: "Dudhouli", nameNp: "दुधौली", type: "Municipality" },
      { name: "Phikkal", nameNp: "फिक्कल", type: "Rural Municipality" },
      { name: "Tinpatan", nameNp: "तिनपाटन", type: "Rural Municipality" },
      { name: "Golanjor", nameNp: "गोलन्जोर", type: "Rural Municipality" },
      {
        name: "Hariharpurgadhi",
        nameNp: "हरिहरपुरगढी",
        type: "Rural Municipality",
      },
      { name: "Junichande", nameNp: "जुनीचण्डे", type: "Rural Municipality" },
    ],
    Sindhupalchok: [
      {
        name: "Chautara Sangachok",
        nameNp: "चौतारा साँगाचोक",
        type: "Municipality",
      },
      { name: "Sindhupalchok", nameNp: "सिन्धुपाल्चोक", type: "Municipality" },
      { name: "Bhotekoshi", nameNp: "भोटेकोशी", type: "Rural Municipality" },
      { name: "Jugal", nameNp: "जुगल", type: "Rural Municipality" },
      {
        name: "Panchpokhari Thangpal",
        nameNp: "पाँचपोखरी थामसल",
        type: "Rural Municipality",
      },
      { name: "Helambu", nameNp: "हेलम्बु", type: "Rural Municipality" },
      { name: "Melamchi", nameNp: "मेलम्ची", type: "Municipality" },
      { name: "Indrawoti", nameNp: "इन्द्रावती", type: "Rural Municipality" },
      {
        name: "Tripurasiddha",
        nameNp: "त्रिपुरासिद्ध",
        type: "Rural Municipality",
      },
    ],
    Dolakha: [
      { name: "Bhimeshwor", nameNp: "भिमेश्वर", type: "Municipality" },
      { name: "Dolakha", nameNp: "दोलखा", type: "Municipality" },
      { name: "Jiri", nameNp: "जिरी", type: "Municipality" },
      { name: "Bigu", nameNp: "विगु", type: "Rural Municipality" },
      { name: "Gaurishankar", nameNp: "गौरीशङ्कर", type: "Rural Municipality" },
      { name: "Khalti", nameNp: "खाल्टी", type: "Rural Municipality" },
      { name: "Melung", nameNp: "मेलुङ", type: "Rural Municipality" },
      { name: "Naina", nameNp: "नैना", type: "Rural Municipality" },
      { name: "Suri", nameNp: "सुरी", type: "Rural Municipality" },
      { name: "Tamakoshi", nameNp: "तामाकोशी", type: "Rural Municipality" },
    ],
    Baglung: [
      { name: "Baglung", nameNp: "बाग्लुङ", type: "Municipality" },
      { name: "Dhorpatan", nameNp: "ढोरपाटन", type: "Municipality" },
      { name: "Galkot", nameNp: "गल्कोट", type: "Municipality" },
      { name: "Jaimuni", nameNp: "जैमुनी", type: "Municipality" },
      { name: "Khatrisan", nameNp: "खत्रीसान", type: "Rural Municipality" },
      { name: "Tara Khola", nameNp: "ताराखोला", type: "Rural Municipality" },
      { name: "Nisi Khola", nameNp: "निसीखोला", type: "Rural Municipality" },
      { name: "Bareng", nameNp: "बरेङ", type: "Rural Municipality" },
    ],
    Gorkha: [
      { name: "Gorkha", nameNp: "गोरखा", type: "Municipality" },
      { name: "Palungtar", nameNp: "पालुङ्टार", type: "Municipality" },
      { name: "Sulikot", nameNp: "सुलीकोट", type: "Rural Municipality" },
      { name: "Ajirkot", nameNp: "अजिरकोट", type: "Rural Municipality" },
      { name: "Siranchok", nameNp: "सिरानचोक", type: "Rural Municipality" },
      {
        name: "Bhimsen Thapa",
        nameNp: "भिमसेन थापा",
        type: "Rural Municipality",
      },
      { name: "Chum Nubri", nameNp: "चुम नुब्री", type: "Rural Municipality" },
      { name: "Dharche", nameNp: "ढङ्ग्रे", type: "Rural Municipality" },
      { name: "Gandaki", nameNp: "गण्डकी", type: "Rural Municipality" },
      { name: "Masma", nameNp: "मास्मा", type: "Rural Municipality" },
    ],
    Kaski: [
      { name: "Pokhara", nameNp: "पोखरा", type: "Metropolitan City" },
      { name: "Annapurna", nameNp: "अन्नपूर्ण", type: "Rural Municipality" },
      { name: "Madi", nameNp: "माडी", type: "Rural Municipality" },
      {
        name: "Machhapuchchhre",
        nameNp: "माछापुच्छ्रे",
        type: "Rural Municipality",
      },
      { name: "Rupa", nameNp: "रूपा", type: "Rural Municipality" },
    ],
    Lamjung: [
      { name: "Besisahar", nameNp: "बेसीशहर", type: "Municipality" },
      {
        name: "Kwhola Satar",
        nameNp: "ख्वाला साटर",
        type: "Rural Municipality",
      },
      { name: "Sundar Bazar", nameNp: "सुन्दर बजार", type: "Municipality" },
      { name: "Dordi", nameNp: "दोर्दी", type: "Rural Municipality" },
      { name: "Dudhpokhari", nameNp: "दुधपोखरी", type: "Rural Municipality" },
      { name: "Gandaki", nameNp: "गण्डकी", type: "Rural Municipality" },
      { name: "Karjan", nameNp: "करजान", type: "Rural Municipality" },
      { name: "Neshwang", nameNp: "नेश्वाङ", type: "Rural Municipality" },
    ],
    Manang: [
      { name: "Chame", nameNp: "चामे", type: "Rural Municipality" },
      { name: "Narpa Bhumi", nameNp: "नर्पा भूमि", type: "Rural Municipality" },
      {
        name: "Manang Ngisyang",
        nameNp: "मनाङ ङिस्याङ",
        type: "Rural Municipality",
      },
    ],
    Mustang: [
      { name: "Jomsom", nameNp: "जोमसोम", type: "Municipality" },
      { name: "Thukla", nameNp: "थुक्ला", type: "Rural Municipality" },
      { name: "Lomanthang", nameNp: "लोमान्थाङ", type: "Rural Municipality" },
      { name: "Gharpajhong", nameNp: "घरपझोङ", type: "Rural Municipality" },
    ],
    Myagdi: [
      { name: "Beni", nameNp: "बेनी", type: "Municipality" },
      { name: "Annapurna", nameNp: "अन्नपूर्ण", type: "Rural Municipality" },
      { name: "Dhaulagiri", nameNp: "ढाका", type: "Rural Municipality" },
      { name: "Mangala", nameNp: "मंगला", type: "Rural Municipality" },
      { name: "Malika", nameNp: "मालिका", type: "Rural Municipality" },
    ],
    "Nawalparasi East": [
      { name: "Kawasoti", nameNp: "कावासोती", type: "Municipality" },
      { name: "Gaindakot", nameNp: "गैंडाकोट", type: "Municipality" },
      { name: "Devchuli", nameNp: "देवचुली", type: "Municipality" },
      { name: "K触发", nameNp: "भूमिकास्थान", type: "Municipality" },
      { name: "Hupsekot", nameNp: "हुप्सेकोट", type: "Rural Municipality" },
      { name: "Madhyabindu", nameNp: "मध्यबिन्दु", type: "Municipality" },
    ],
    "Nawalparasi West": [
      { name: "Ramgram", nameNp: "रामग्राम", type: "Municipality" },
      { name: "Swasti", nameNp: "स्वास्थी", type: "Municipality" },
      {
        name: "Palhi Nandan",
        nameNp: "पाल्ही नन्दन",
        type: "Rural Municipality",
      },
      { name: "Saradan", nameNp: "सरादान", type: "Rural Municipality" },
      { name: "Bardaghat", nameNp: "बर्दघाट", type: "Municipality" },
      { name: "Pratappur", nameNp: "प्रतापपुर", type: "Rural Municipality" },
      { name: "Sani Bheri", nameNp: "सानी भेरी", type: "Rural Municipality" },
    ],
    Parbat: [
      { name: "Kushma", nameNp: "कुश्मा", type: "Municipality" },
      { name: "Phalebas", nameNp: "फालेबास", type: "Municipality" },
      { name: "Mahashila", nameNp: "महाशिला", type: "Rural Municipality" },
      { name: "Paiyun", nameNp: "पाईँ", type: "Rural Municipality" },
      { name: "Bihadi", nameNp: "बिहादी", type: "Rural Municipality" },
      { name: "Modi", nameNp: "मोडी", type: "Rural Municipality" },
      { name: "Jaljala", nameNp: "जलजला", type: "Rural Municipality" },
    ],
    Syangja: [
      { name: "Syanjabazar", nameNp: "स्याङ्जा बजार", type: "Municipality" },
      { name: "Chandrakot", nameNp: "चन्द्रकोट", type: "Rural Municipality" },
      { name: "Bhirkot", nameNp: "भीरकोट", type: "Municipality" },
      { name: "Galyang", nameNp: "गल्याङ", type: "Municipality" },
      { name: "Harinas", nameNp: "हरिनास", type: "Rural Municipality" },
      { name: "K大神", nameNp: "कपिलेश्वर", type: "Municipality" },
      { name: "Walling", nameNp: "वालिङ", type: "Municipality" },
      { name: "Phedikhola", nameNp: "फेदीखोला", type: "Rural Municipality" },
      {
        name: "Arjun Chaupari",
        nameNp: "अर्जुन चौपारी",
        type: "Rural Municipality",
      },
      { name: "Biruwa", nameNp: "बिरुवा", type: "Rural Municipality" },
    ],
    Tanahun: [
      { name: "Damauli", nameNp: "दमौली", type: "Municipality" },
      { name: "Byas", nameNp: "व्यास", type: "Municipality" },
      { name: "Devghat", nameNp: "देवघाट", type: "Municipality" },
      { name: "Rishing", nameNp: "रिसिङ", type: "Rural Municipality" },
      {
        name: "Aanbookhairava",
        nameNp: "आनबोेखैराव",
        type: "Rural Municipality",
      },
      { name: "Bandipur", nameNp: "बान्डीपुर", type: "Rural Municipality" },
      { name: "Ghiring", nameNp: "घिरिङ", type: "Rural Municipality" },
      { name: "K触发", nameNp: "भूमिकास्थान", type: "Municipality" },
      {
        name: "Shukeshrashi",
        nameNp: "शुक्लेश्वरी",
        type: "Rural Municipality",
      },
      { name: "Myalng", nameNp: "म्यालङ", type: "Rural Municipality" },
    ],
    Arghakhanchi: [
      { name: "Sandhikharka", nameNp: "सन्धिखर्क", type: "Municipality" },
      { name: "Sitganga", nameNp: "सीतागढ", type: "Municipality" },
      { name: "Bhumikasthan", nameNp: "भूमिकास्थान", type: "Municipality" },
      { name: "Chhatraganj", nameNp: "छत्रगञ्ज", type: "Rural Municipality" },
      { name: "Malarani", nameNp: "मलारानी", type: "Rural Municipality" },
      { name: "Panini", nameNp: "पानिनी", type: "Rural Municipality" },
    ],
    Banke: [
      { name: "Nepalgunj", nameNp: "नेपालगञ्ज", type: "Sub-Metropolitan City" },
      { name: "Kohalpur", nameNp: "कोहलपुर", type: "Municipality" },
      { name: "Rapti Sonari", nameNp: "राप्ती सोनारी", type: "Municipality" },
      { name: "Duduwa", nameNp: "दुधौनी", type: "Rural Municipality" },
      { name: "Jalari", nameNp: "जलजला", type: "Rural Municipality" },
      { name: "Narainapur", nameNp: "नरायणपुर", type: "Rural Municipality" },
      { name: "Baijanath", nameNp: "बैजनाथ", type: "Rural Municipality" },
    ],
    Bardiya: [
      { name: "Gulariya", nameNp: "गुलरिया", type: "Municipality" },
      { name: "Bansgadhi", nameNp: "बाँसगढी", type: "Municipality" },
      { name: "Barbardiya", nameNp: "बर्बरीया", type: "Municipality" },
      { name: "Rajapur", nameNp: "राजापुर", type: "Municipality" },
      { name: "Thakurbaba", nameNp: "ठाकुरबाबा", type: "Municipality" },
      { name: "Madhuwan", nameNp: "मधुवन", type: "Municipality" },
      { name: "Geruwa", nameNp: "गेरुवा", type: "Rural Municipality" },
      { name: "Badhaiyatal", nameNp: "बधाईताल", type: "Rural Municipality" },
    ],
    Butwal: [
      { name: "Butwal", nameNp: "बुटवल", type: "Sub-Metropolitan City" },
      { name: "Siddharthanagar", nameNp: "सिद्धार्थनगर", type: "Municipality" },
      { name: "Devdaha", nameNp: "देवदह", type: "Municipality" },
      {
        name: "Lumbini Sanskritik",
        nameNp: "लुम्बिनी सांस्कृतिक",
        type: "Municipality",
      },
      { name: "Sainamaina", nameNp: "सैनमैन", type: "Municipality" },
      { name: "Kotahimai", nameNp: "कोटाहिमाई", type: "Rural Municipality" },
      { name: "Marchawari", nameNp: "मर्चवारी", type: "Rural Municipality" },
      { name: "Rohini", nameNp: "रोहीनी", type: "Rural Municipality" },
      { name: "Siddharthanagar", nameNp: "सिद्धार्थनगर", type: "Municipality" },
    ],
    Dang: [
      { name: "Ghorahi", nameNp: "घोराही", type: "Sub-Metropolitan City" },
      { name: "Tulsipur", nameNp: "तुलसीपुर", type: "Sub-Metropolitan City" },
      { name: "Lamahi", nameNp: "लमही", type: "Municipality" },
      { name: "Banglachuli", nameNp: "बगलाचुली", type: "Rural Municipality" },
      { name: "Dangisharan", nameNp: "दाङ्गीशरण", type: "Rural Municipality" },
      { name: "Gadhawa", nameNp: "गढवा", type: "Rural Municipality" },
      { name: "Rajpur", nameNp: "राजपुर", type: "Rural Municipality" },
      { name: "Rapti", nameNp: "राप्ती", type: "Rural Municipality" },
      { name: "Shantinagar", nameNp: "शान्तिनगर", type: "Rural Municipality" },
      { name: "Babai", nameNp: "बाँै", type: "Rural Municipality" },
    ],
    "East Rukum": [
      { name: "Rukumkot", nameNp: "रुकुम कोट", type: "Municipality" },
      { name: "Banfikot", nameNp: "बान्फीकोट", type: "Rural Municipality" },
      { name: "Sani Rukum", nameNp: "सानी रुकुम", type: "Rural Municipality" },
      { name: "Kol", nameNp: "कोल", type: "Rural Municipality" },
      { name: "Musikot", nameNp: "मुसिकोट", type: "Municipality" },
      { name: "Tribeni", nameNp: "त्रिवेणी", type: "Rural Municipality" },
    ],
    Gulmi: [
      { name: "Tamghas", nameNp: "तम्घास", type: "Municipality" },
      { name: "Resunga", nameNp: "रेसुङ्गा", type: "Municipality" },
      { name: "Chhatrakot", nameNp: "छत्रकोट", type: "Rural Municipality" },
      { name: "Dhurkot", nameNp: "ढूरकोट", type: "Rural Municipality" },
      { name: "Gulmi", nameNp: "गुल्मी", type: "Rural Municipality" },
      { name: "Isma", nameNp: "इस्मा", type: "Rural Municipality" },
      { name: "Kaligandaki", nameNp: "कालीगण्डकी", type: "Rural Municipality" },
      { name: "Madane", nameNp: "मदाने", type: "Rural Municipality" },
      { name: "Malika", nameNp: "मालिका", type: "Rural Municipality" },
      { name: "Musikot", nameNp: "मुसिकोट", type: "Municipality" },
      { name: "Ruru", nameNp: "रूरू", type: "Rural Municipality" },
    ],
    Kapilvastu: [
      { name: "Kapilvastu", nameNp: "कपिलवस्तु", type: "Municipality" },
      { name: "Banganga", nameNp: "बाँगका", type: "Municipality" },
      { name: "Biharwa", nameNp: "बिहारवा", type: "Municipality" },
      { name: "Buddhabhumi", nameNp: "बुद्धभूमी", type: "Municipality" },
      { name: "Maharajganj", nameNp: "महाराजगञ्ज", type: "Municipality" },
      { name: "Smarat", nameNp: "शमरात", type: "Municipality" },
      { name: "Yashodhara", nameNp: "यशोधरा", type: "Municipality" },
      { name: "Krishnanagar", nameNp: "कृष्णनगर", type: "Municipality" },
      { name: "Maihariwa", nameNp: "मैहरीवा", type: "Rural Municipality" },
      { name: "Vijaipur", nameNp: "विजयपुर", type: "Municipality" },
    ],
    Nawalparasi: [
      { name: "Kawasoti", nameNp: "कावासोती", type: "Municipality" },
      { name: "Gaindakot", nameNp: "गैंडाकोट", type: "Municipality" },
      { name: "Devachuli", nameNp: "देवचुली", type: "Municipality" },
      { name: "Madhyabindu", nameNp: "मध्यबिन्दु", type: "Municipality" },
      { name: "Hupsekot", nameNp: "हुप्सेकोट", type: "Rural Municipality" },
      { name: "Balganga", nameNp: "बलगङ्गा", type: "Rural Municipality" },
    ],
    Palpa: [
      { name: "Tansen", nameNp: "तानसेन", type: "Municipality" },
      { name: "Rampur", nameNp: "रामपुर", type: "Municipality" },
      { name: "Bagnaskali", nameNp: "बगनासकाली", type: "Rural Municipality" },
      { name: "Bhumdi", nameNp: "भुम्दी", type: "Rural Municipality" },
      { name: "D数日", nameNp: "देउराली", type: "Municipality" },
      { name: "Mathagadi", nameNp: "माथागढी", type: "Rural Municipality" },
      { name: "Nipane", nameNp: "निपाने", type: "Rural Municipality" },
      { name: "Rambha", nameNp: "राम्भा", type: "Rural Municipality" },
      { name: "Sandhikharka", nameNp: "सन्धिखर्क", type: "Municipality" },
      { name: "Tinau", nameNp: "तिनौनी", type: "Rural Municipality" },
    ],
    Pyuthan: [
      { name: "Pyuthan", nameNp: "प्यूठान", type: "Municipality" },
      { name: "Swargadwari", nameNp: "स्वर्गद्वारी", type: "Municipality" },
      { name: "Gaumukhi", nameNp: "गौमुखी", type: "Rural Municipality" },
      { name: "Jhimar", nameNp: "झिमर", type: "Rural Municipality" },
      { name: "Mandavi", nameNp: "माण्डवी", type: "Rural Municipality" },
      { name: "Mallarani", nameNp: "मल्लरानी", type: "Rural Municipality" },
      { name: "Nauwang", nameNp: "नौवाङ", type: "Rural Municipality" },
      { name: "Panchamul", nameNp: "पञ्चमूल", type: "Rural Municipality" },
      { name: "Sarumarani", nameNp: "सरुमारानी", type: "Rural Municipality" },
    ],
    Rupandehi: [
      { name: "Butwal", nameNp: "बुटवल", type: "Sub-Metropolitan City" },
      { name: "Siddharthanagar", nameNp: "सिद्धार्थनगर", type: "Municipality" },
      { name: "Bhairahawa", nameNp: "भैरहवा", type: "Sub-Metropolitan City" },
      {
        name: "Lumbini Sanskritik",
        nameNp: "लुम्बिनी सांस्कृतिक",
        type: "Municipality",
      },
      { name: "Sainamaina", nameNp: "सैनमैन", type: "Municipality" },
      { name: "Devdaha", nameNp: "देवदह", type: "Municipality" },
      { name: "Gaidahawa", nameNp: "गैडहवा", type: "Rural Municipality" },
      { name: "Kotawa", nameNp: "कोटवा", type: "Rural Municipality" },
      { name: "Mayadevi", nameNp: "मायादेवी", type: "Rural Municipality" },
      { name: "Omsatiya", nameNp: "ओमसतिया", type: "Rural Municipality" },
      { name: "Salmari", nameNp: "सल्मारी", type: "Rural Municipality" },
      { name: "Shankarnagar", nameNp: "शंकरनगर", type: "Rural Municipality" },
      { name: "Suddhodhan", nameNp: "सुद्धोधान", type: "Rural Municipality" },
      { name: "Tilottama", nameNp: "तिलोतमा", type: "Municipality" },
    ],
    Dailekh: [
      { name: "Dailekh", nameNp: "दैलेख", type: "Municipality" },
      { name: "Narayan", nameNp: "नारायण", type: "Municipality" },
      { name: "Aalital", nameNp: "आलिताल", type: "Rural Municipality" },
      { name: "Bhairavi", nameNp: "भैरवी", type: "Rural Municipality" },
      {
        name: "Chamunda Bindrasaini",
        nameNp: "चामुण्डा बिन्द्रसैनी",
        type: "Municipality",
      },
      { name: "Dungeshwor", nameNp: "दुनेश्वर", type: "Rural Municipality" },
      { name: "Gurans", nameNp: "गुराँस", type: "Rural Municipality" },
      { name: "Jagannath", nameNp: "जगन्नाथ", type: "Rural Municipality" },
      { name: "Khiwang", nameNp: "खिवाङ", type: "Rural Municipality" },
      { name: "Mahawai", nameNp: "महावै", type: "Rural Municipality" },
      { name: "Naumule", nameNp: "नाउम्ले", type: "Rural Municipality" },
      {
        name: "Thantikandh",
        nameNp: "थान्तिकाण्ड",
        type: "Rural Municipality",
      },
    ],
    Dolpa: [
      { name: "Dolpa", nameNp: "डोल्पा", type: "Municipality" },
      { name: "Dunai", nameNp: "दुनै", type: "Municipality" },
      { name: "Shey Phoksundo", nameNp: "शे फोक्सुण्डो", type: "Municipality" },
      {
        name: "Tripura Sundari",
        nameNp: "त्रिपुरा सुन्दरी",
        type: "Municipality",
      },
      { name: "Chharka", nameNp: "छार्का", type: "Rural Municipality" },
      { name: "Mugling", nameNp: "मुग्लिङ", type: "Rural Municipality" },
    ],
    Jajarkot: [
      { name: "Jajarkot", nameNp: "जाजरकोट", type: "Municipality" },
      { name: "Chhedagadh", nameNp: "छेडागढ", type: "Municipality" },
      { name: "Kushe", nameNp: "कुशे", type: "Rural Municipality" },
      { name: "Barekot", nameNp: "बारेकोट", type: "Rural Municipality" },
      { name: "Shivalaya", nameNp: "शिवालय", type: "Rural Municipality" },
      { name: "Talegaun", nameNp: "तालेगाउँ", type: "Rural Municipality" },
    ],
    Jumla: [
      { name: "Jumla", nameNp: "जुम्ला", type: "Municipality" },
      { name: "Chandannath", nameNp: "चन्दननाथ", type: "Municipality" },
      { name: "Guthichaur", nameNp: "गुठीचौर", type: "Rural Municipality" },
      { name: "Hima", nameNp: "हिमा", type: "Rural Municipality" },
      {
        name: "Kanakasundari",
        nameNp: "कनकासुन्दरी",
        type: "Rural Municipality",
      },
      { name: "Kankre", nameNp: "काँकरे", type: "Rural Municipality" },
      { name: "Patarasi", nameNp: "पातारासी", type: "Rural Municipality" },
      { name: "Sinja", nameNp: "सिंजा", type: "Rural Municipality" },
      { name: "Tatopani", nameNp: "तातोपानी", type: "Rural Municipality" },
    ],
    Kalikot: [
      { name: "Manma", nameNp: "मन्मा", type: "Municipality" },
      { name: "Kalika", nameNp: "कालिका", type: "Municipality" },
      { name: "Pabera", nameNp: "पाबेरा", type: "Rural Municipality" },
      { name: "Raskot", nameNp: "रास्कोट", type: "Rural Municipality" },
      {
        name: "Sana Talchhit",
        nameNp: "साना तलचित",
        type: "Rural Municipality",
      },
      {
        name: "Shuva Kalika",
        nameNp: "शुवा कालिका",
        type: "Rural Municipality",
      },
      { name: "Tilagufa", nameNp: "तिलागुफा", type: "Municipality" },
      { name: "Naraharinath", nameNp: "नरहरिनाथ", type: "Municipality" },
    ],
    Mugu: [
      { name: "Gamgadhi", nameNp: "गमगढी", type: "Municipality" },
      {
        name: "Mugum Karmarong",
        nameNp: "मुगुम कर्मारोङ",
        type: "Rural Municipality",
      },
      { name: "Mugu", nameNp: "मुगु", type: "Rural Municipality" },
      { name: "Khatyad", nameNp: "खत्याड", type: "Rural Municipality" },
      { name: "Soru", nameNp: "सोरु", type: "Rural Municipality" },
    ],
    Salyan: [
      { name: "Salyan", nameNp: "सल्यान", type: "Municipality" },
      { name: "Bagar", nameNp: "बगर", type: "Municipality" },
      { name: "Chhayachhetra", nameNp: "छयाछेत्र", type: "Rural Municipality" },
      { name: "Darma", nameNp: "दर्मा", type: "Rural Municipality" },
      { name: "Dhorchaur", nameNp: "ढोरचौर", type: "Rural Municipality" },
      { name: "Kavre", nameNp: "कावे", type: "Rural Municipality" },
      { name: "Kubhinde", nameNp: "कुँविन्डे", type: "Rural Municipality" },
      { name: "Kulang", nameNp: "कुलाङ", type: "Rural Municipality" },
      { name: "Shaan", nameNp: "श्यान", type: "Rural Municipality" },
      { name: "Swar", nameNp: "स्वार", type: "Rural Municipality" },
      { name: "Tribeni", nameNp: "त्रिवेणी", type: "Municipality" },
    ],
    Surkhet: [
      { name: "Surkhet", nameNp: "सुर्खेत", type: "Municipality" },
      {
        name: "Birendranagar",
        nameNp: "वीरेन्द्रनगर",
        type: "Sub-Metropolitan City",
      },
      { name: "Bheriganga", nameNp: "भेरीगङ्गा", type: "Municipality" },
      { name: "Chaukune", nameNp: "चौउकुने", type: "Rural Municipality" },
      { name: "Gurbikot", nameNp: "गुर्बिकोट", type: "Municipality" },
      { name: "Lekbeshi", nameNp: "लेकबेशी", type: "Municipality" },
      { name: "Panchapuri", nameNp: "पञ्चपुरी", type: "Rural Municipality" },
      { name: "Simta", nameNp: "सिम्ता", type: "Rural Municipality" },
    ],
    "West Rukum": [
      { name: "Musikot", nameNp: "मुसिकोट", type: "Municipality" },
      { name: "Tribeni", nameNp: "त्रिवेणी", type: "Rural Municipality" },
      { name: "Banfikot", nameNp: "बान्फीकोट", type: "Rural Municipality" },
      { name: "Kol", nameNp: "कोल", type: "Rural Municipality" },
      { name: "Sani Rukum", nameNp: "सानी रुकुम", type: "Rural Municipality" },
    ],
    Humla: [
      { name: "Simikot", nameNp: "सिमिकोट", type: "Municipality" },
      { name: "Khandbari", nameNp: "खाँडबराल", type: "Rural Municipality" },
      { name: "Marmak", nameNp: "मार्माक", type: "Rural Municipality" },
      { name: "Namkha", nameNp: "नाम्खा", type: "Rural Municipality" },
      { name: "Sarkegad", nameNp: "सार्केगड", type: "Rural Municipality" },
      { name: "Tanju", nameNp: "ताञ्जु", type: "Rural Municipality" },
      { name: "Chhankheli", nameNp: "छाँखली", type: "Rural Municipality" },
    ],
    Achham: [
      { name: "Mangalsen", nameNp: "मंगलसेन", type: "Municipality" },
      { name: "Kamala", nameNp: "कमला", type: "Municipality" },
      {
        name: "Bannigadhi Jayagadh",
        nameNp: "बान्नीगढी जयगढ",
        type: "Rural Municipality",
      },
      { name: "Chaurpati", nameNp: "चौरपाटी", type: "Rural Municipality" },
      { name: "Dhakari", nameNp: "ढकारी", type: "Rural Municipality" },
      { name: "Kamalakhada", nameNp: "कमलाखडा", type: "Rural Municipality" },
      { name: "Mellep", nameNp: "मेल्लेप", type: "Rural Municipality" },
      {
        name: "Murkidedaha",
        nameNp: "मुर्की देहा",
        type: "Rural Municipality",
      },
      { name: "Sanphebagar", nameNp: "सानपेबाँगर", type: "Municipality" },
      { name: "Turmakhand", nameNp: "तुर्माखण्ड", type: "Rural Municipality" },
    ],
    Baitadi: [
      { name: "Dasharathchand", nameNp: "दशरथचन्द", type: "Municipality" },
      { name: "Patan", nameNp: "पाटन", type: "Municipality" },
      { name: "Baitadi", nameNp: "बैतडी", type: "Municipality" },
      { name: "Dilasaini", nameNp: "दिलासैनी", type: "Municipality" },
      {
        name: "Dogada Kedar",
        nameNp: "दोगडा केदार",
        type: "Rural Municipality",
      },
      { name: "Jaya Prithvi", nameNp: "जय प्रिथ्वी", type: "Municipality" },
      { name: "Mahakali", nameNp: "महाकाली", type: "Municipality" },
      { name: "Nigina", nameNp: "निगीना", type: "Rural Municipality" },
      { name: "Puchaudi", nameNp: "पुचौडी", type: "Rural Municipality" },
      { name: "Shivnagar", nameNp: "शिवनगर", type: "Rural Municipality" },
    ],
    Bajhang: [
      { name: "Chainpur", nameNp: "चैनपुर", type: "Municipality" },
      { name: "Darchula", nameNp: "दार्चुला", type: "Municipality" },
      { name: "Jayaprithivi", nameNp: "जयपृथ्वी", type: "Municipality" },
      { name: "Kahar", nameNp: "काहार", type: "Rural Municipality" },
      { name: "Lungalunga", nameNp: "लुंगालुंगा", type: "Rural Municipality" },
      { name: "Mauga", nameNp: "मौगा", type: "Rural Municipality" },
      { name: "Sreekhand", nameNp: "श्रीखण्ड", type: "Rural Municipality" },
      { name: "Thalara", nameNp: "थलारा", type: "Rural Municipality" },
      { name: "Tippani", nameNp: "तिप्पानी", type: "Rural Municipality" },
    ],
    Bajura: [
      { name: "Martadi", nameNp: "मार्तडी", type: "Municipality" },
      { name: "Bajura", nameNp: "बाजुरा", type: "Municipality" },
      { name: "Budhinanda", nameNp: "बुढीनन्दा", type: "Municipality" },
      { name: "Chhededaha", nameNp: "छेडेदह", type: "Rural Municipality" },
      { name: "Gaumul", nameNp: "गौमूल", type: "Rural Municipality" },
      { name: "Himali", nameNp: "हिमाली", type: "Rural Municipality" },
      { name: "Jagannath", nameNp: "जगन्नाथ", type: "Rural Municipality" },
      { name: "Swamibu", nameNp: "स्वामीबु", type: "Rural Municipality" },
      { name: "Triveni", nameNp: "त्रिवेणी", type: "Rural Municipality" },
    ],
    Dadeldhura: [
      { name: "Amargadhi", nameNp: "अमरगढी", type: "Municipality" },
      { name: "Ajaymeru", nameNp: "अजयमेरु", type: "Rural Municipality" },
      { name: "Bhageshwor", nameNp: "भागेश्वर", type: "Rural Municipality" },
      { name: "Birapatal", nameNp: "बिरापताल", type: "Rural Municipality" },
      {
        name: "Ganyapadhura",
        nameNp: "गन्यापाधुरा",
        type: "Rural Municipality",
      },
      { name: "Jyamire", nameNp: "ज्यामिरे", type: "Rural Municipality" },
      { name: "Kailash", nameNp: "कैलाश", type: "Rural Municipality" },
      { name: "Nagog", nameNp: "नागोग", type: "Rural Municipality" },
      { name: "Parshuram", nameNp: "पर्शुराम", type: "Rural Municipality" },
    ],
    Darchula: [
      { name: "Darchula", nameNp: "दार्चुला", type: "Municipality" },
      { name: "Mahakali", nameNp: "महाकाली", type: "Municipality" },
      { name: "Apihimal", nameNp: "अपिहिमाल", type: "Rural Municipality" },
      { name: "Boom", nameNp: "बूम", type: "Rural Municipality" },
      { name: "Duhun", nameNp: "दुहुन", type: "Rural Municipality" },
      { name: "Marma", nameNp: "मार्मा", type: "Rural Municipality" },
      { name: "Naugad", nameNp: "नौगाड", type: "Rural Municipality" },
      { name: "Nigidada", nameNp: "निगीदादा", type: "Rural Municipality" },
      { name: "Shailyashikhar", nameNp: "शैल्यशिखर", type: "Municipality" },
      { name: "Sira", nameNp: "सिरा", type: "Rural Municipality" },
    ],
    Doti: [
      {
        name: "Dipayal Silgadhi",
        nameNp: "दिपायल सिलगढी",
        type: "Municipality",
      },
      { name: "Aadarsha", nameNp: "आदर्श", type: "Municipality" },
      { name: "Badikedar", nameNp: "बाडीकेदार", type: "Rural Municipality" },
      { name: "Bogtan", nameNp: "बोगटान", type: "Rural Municipality" },
      { name: "Doti", nameNp: "डोटी", type: "Municipality" },
      { name: "Jal", nameNp: "जल", type: "Rural Municipality" },
      { name: "K I Singh", nameNp: "के आई सिंह", type: "Rural Municipality" },
      {
        name: "Purbichauki",
        nameNp: "पूर्वी चौकी",
        type: "Rural Municipality",
      },
      { name: "Sayal", nameNp: "सायल", type: "Rural Municipality" },
      { name: "Shikhar", nameNp: "शिखर", type: "Rural Municipality" },
    ],
    Kailali: [
      { name: "Dhangadhi", nameNp: "धनगढी", type: "Sub-Metropolitan City" },
      { name: "Tikapur", nameNp: "टिकापुर", type: "Municipality" },
      { name: "Bhajani", nameNp: "भजनी", type: "Municipality" },
      { name: "Chure", nameNp: "चुरे", type: "Rural Municipality" },
      { name: "Dododhara", nameNp: "दोडोधरा", type: "Rural Municipality" },
      { name: "Gauriganga", nameNp: "गौरिगंगा", type: "Municipality" },
      { name: "Ghodaghodi", nameNp: "घोडाघोडी", type: "Municipality" },
      { name: "Janaki", nameNp: "जानकी", type: "Rural Municipality" },
      { name: "Kailari", nameNp: "कैलारी", type: "Rural Municipality" },
      { name: "Lamar", nameNp: "लामरुङ", type: "Rural Municipality" },
      { name: "Mohanyal", nameNp: "मोहन्याल", type: "Rural Municipality" },
      { name: "Rapatgaun", nameNp: "राप्तागाउँ", type: "Rural Municipality" },
      { name: "Sugarkhal", nameNp: "सुगर्खाल", type: "Rural Municipality" },
      { name: "Lamki Chuha", nameNp: "लम्की चुहा", type: "Municipality" },
    ],
    Kanchanpur: [
      { name: "Bhimdatta", nameNp: "भिमदत्ता", type: "Municipality" },
      { name: "Bedkot", nameNp: "बेडकोट", type: "Municipality" },
      { name: "Beldandi", nameNp: "बेल्डण्डी", type: "Rural Municipality" },
      { name: "Birendranagar", nameNp: "वीरेन्द्रनगर", type: "Municipality" },
      {
        name: "Dodhara Chandani",
        nameNp: "दोधरा चाँदनी",
        type: "Municipality",
      },
      { name: "Krishnapur", nameNp: "कृष्णपुर", type: "Municipality" },
      { name: "Laljhadi", nameNp: "लालझाडी", type: "Rural Municipality" },
      { name: "Mahakali", nameNp: "महाकाली", type: "Municipality" },
      { name: "Punarbas", nameNp: "पुनर्वास", type: "Municipality" },
      { name: "Shuklaphanta", nameNp: "शुक्लाफाँटा", type: "Municipality" },
    ],
  },
};

async function main() {
  console.log("Seeding Nepal geographic data...");

  for (const provinceData of nepalGeo.provinces) {
    await prisma.province.upsert({
      where: { name: provinceData.name },
      update: { nameNp: provinceData.nameNp },
      create: provinceData,
    });
    console.log(`  Province: ${provinceData.name}`);
  }

  for (const districtData of nepalGeo.districts) {
    const province = await prisma.province.findUnique({
      where: { name: districtData.province },
    });
    if (!province) {
      console.warn(`  Province not found: ${districtData.province}`);
      continue;
    }
    await prisma.district.upsert({
      where: {
        provinceId_name: {
          provinceId: province.id,
          name: districtData.name,
        },
      },
      update: { nameNp: districtData.nameNp },
      create: {
        name: districtData.name,
        nameNp: districtData.nameNp,
        provinceId: province.id,
      },
    });
    console.log(`  District: ${districtData.name}`);
  }

  for (const [districtName, municipalities] of Object.entries(
    nepalGeo.municipalities,
  )) {
    const district = await prisma.district.findFirst({
      where: { name: districtName },
    });
    if (!district) {
      console.warn(`  District not found: ${districtName}`);
      continue;
    }
    for (const munData of municipalities) {
      await prisma.municipality.upsert({
        where: {
          districtId_name: {
            districtId: district.id,
            name: munData.name,
          },
        },
        update: { nameNp: munData.nameNp, type: munData.type },
        create: {
          name: munData.name,
          nameNp: munData.nameNp,
          type: munData.type,
          districtId: district.id,
        },
      });
    }
    console.log(`  Municipality for ${districtName}: ${municipalities.length}`);
  }

  console.log("Seed complete!");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
