/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodosRouteImport } from './routes/todos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppLoansRouteImport } from './routes/_app/loans'
import { Route as AppKycRouteImport } from './routes/_app/kyc'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCustomersRouteImport } from './routes/_app/customers'
import { Route as AppContactsRouteImport } from './routes/_app.contacts'
import { Route as AppLoansIdRouteImport } from './routes/_app/loans/$id'
import { Route as AppKycIdRouteImport } from './routes/_app/kyc/$id'
import { Route as AppContactsNewRouteImport } from './routes/_app.contacts.new'
import { Route as AppContactsIdEditRouteImport } from './routes/_app.contacts.$id.edit'

const TodosRoute = TodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLoansRoute = AppLoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => AppRoute,
} as any)
const AppKycRoute = AppKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppContactsRoute = AppContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AppRoute,
} as any)
const AppLoansIdRoute = AppLoansIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppLoansRoute,
} as any)
const AppKycIdRoute = AppKycIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppKycRoute,
} as any)
const AppContactsNewRoute = AppContactsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppContactsRoute,
} as any)
const AppContactsIdEditRoute = AppContactsIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => AppContactsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/todos': typeof TodosRoute
  '/contacts': typeof AppContactsRouteWithChildren
  '/customers': typeof AppCustomersRoute
  '/dashboard': typeof AppDashboardRoute
  '/kyc': typeof AppKycRouteWithChildren
  '/loans': typeof AppLoansRouteWithChildren
  '/contacts/new': typeof AppContactsNewRoute
  '/kyc/$id': typeof AppKycIdRoute
  '/loans/$id': typeof AppLoansIdRoute
  '/contacts/$id/edit': typeof AppContactsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/todos': typeof TodosRoute
  '/contacts': typeof AppContactsRouteWithChildren
  '/customers': typeof AppCustomersRoute
  '/dashboard': typeof AppDashboardRoute
  '/kyc': typeof AppKycRouteWithChildren
  '/loans': typeof AppLoansRouteWithChildren
  '/contacts/new': typeof AppContactsNewRoute
  '/kyc/$id': typeof AppKycIdRoute
  '/loans/$id': typeof AppLoansIdRoute
  '/contacts/$id/edit': typeof AppContactsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/todos': typeof TodosRoute
  '/_app/contacts': typeof AppContactsRouteWithChildren
  '/_app/customers': typeof AppCustomersRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/kyc': typeof AppKycRouteWithChildren
  '/_app/loans': typeof AppLoansRouteWithChildren
  '/_app/contacts/new': typeof AppContactsNewRoute
  '/_app/kyc/$id': typeof AppKycIdRoute
  '/_app/loans/$id': typeof AppLoansIdRoute
  '/_app/contacts/$id/edit': typeof AppContactsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/todos'
    | '/contacts'
    | '/customers'
    | '/dashboard'
    | '/kyc'
    | '/loans'
    | '/contacts/new'
    | '/kyc/$id'
    | '/loans/$id'
    | '/contacts/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/todos'
    | '/contacts'
    | '/customers'
    | '/dashboard'
    | '/kyc'
    | '/loans'
    | '/contacts/new'
    | '/kyc/$id'
    | '/loans/$id'
    | '/contacts/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/todos'
    | '/_app/contacts'
    | '/_app/customers'
    | '/_app/dashboard'
    | '/_app/kyc'
    | '/_app/loans'
    | '/_app/contacts/new'
    | '/_app/kyc/$id'
    | '/_app/loans/$id'
    | '/_app/contacts/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  TodosRoute: typeof TodosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/todos': {
      id: '/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof TodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/loans': {
      id: '/_app/loans'
      path: '/loans'
      fullPath: '/loans'
      preLoaderRoute: typeof AppLoansRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kyc': {
      id: '/_app/kyc'
      path: '/kyc'
      fullPath: '/kyc'
      preLoaderRoute: typeof AppKycRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers': {
      id: '/_app/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contacts': {
      id: '/_app/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AppContactsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/loans/$id': {
      id: '/_app/loans/$id'
      path: '/$id'
      fullPath: '/loans/$id'
      preLoaderRoute: typeof AppLoansIdRouteImport
      parentRoute: typeof AppLoansRoute
    }
    '/_app/kyc/$id': {
      id: '/_app/kyc/$id'
      path: '/$id'
      fullPath: '/kyc/$id'
      preLoaderRoute: typeof AppKycIdRouteImport
      parentRoute: typeof AppKycRoute
    }
    '/_app/contacts/new': {
      id: '/_app/contacts/new'
      path: '/new'
      fullPath: '/contacts/new'
      preLoaderRoute: typeof AppContactsNewRouteImport
      parentRoute: typeof AppContactsRoute
    }
    '/_app/contacts/$id/edit': {
      id: '/_app/contacts/$id/edit'
      path: '/$id/edit'
      fullPath: '/contacts/$id/edit'
      preLoaderRoute: typeof AppContactsIdEditRouteImport
      parentRoute: typeof AppContactsRoute
    }
  }
}

interface AppContactsRouteChildren {
  AppContactsNewRoute: typeof AppContactsNewRoute
  AppContactsIdEditRoute: typeof AppContactsIdEditRoute
}

const AppContactsRouteChildren: AppContactsRouteChildren = {
  AppContactsNewRoute: AppContactsNewRoute,
  AppContactsIdEditRoute: AppContactsIdEditRoute,
}

const AppContactsRouteWithChildren = AppContactsRoute._addFileChildren(
  AppContactsRouteChildren,
)

interface AppKycRouteChildren {
  AppKycIdRoute: typeof AppKycIdRoute
}

const AppKycRouteChildren: AppKycRouteChildren = {
  AppKycIdRoute: AppKycIdRoute,
}

const AppKycRouteWithChildren =
  AppKycRoute._addFileChildren(AppKycRouteChildren)

interface AppLoansRouteChildren {
  AppLoansIdRoute: typeof AppLoansIdRoute
}

const AppLoansRouteChildren: AppLoansRouteChildren = {
  AppLoansIdRoute: AppLoansIdRoute,
}

const AppLoansRouteWithChildren = AppLoansRoute._addFileChildren(
  AppLoansRouteChildren,
)

interface AppRouteChildren {
  AppContactsRoute: typeof AppContactsRouteWithChildren
  AppCustomersRoute: typeof AppCustomersRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppKycRoute: typeof AppKycRouteWithChildren
  AppLoansRoute: typeof AppLoansRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppContactsRoute: AppContactsRouteWithChildren,
  AppCustomersRoute: AppCustomersRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppKycRoute: AppKycRouteWithChildren,
  AppLoansRoute: AppLoansRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  TodosRoute: TodosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
