/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppPassbookRouteImport } from './routes/app/passbook'
import { Route as AppNotificationsRouteImport } from './routes/app/notifications'
import { Route as AppLoansRouteImport } from './routes/app/loans'
import { Route as AppKycRouteImport } from './routes/app/kyc'
import { Route as AppDashboardRouteImport } from './routes/app/dashboard'
import { Route as AppLoansNewRouteImport } from './routes/app/loans/new'
import { Route as AppLoansIdRouteImport } from './routes/app/loans/$id'
import { Route as AppKycSignatureRouteImport } from './routes/app/kyc/signature'
import { Route as AppKycNomineeRouteImport } from './routes/app/kyc/nominee'
import { Route as AppKycMandatoryRouteImport } from './routes/app/kyc/mandatory'
import { Route as AppKycBasicInfoRouteImport } from './routes/app/kyc/basic-info'
import { Route as AppLoansIdSuccessRouteImport } from './routes/app/loans/$id/success'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPassbookRoute = AppPassbookRouteImport.update({
  id: '/passbook',
  path: '/passbook',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppLoansRoute = AppLoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => AppRoute,
} as any)
const AppKycRoute = AppKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppLoansNewRoute = AppLoansNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppLoansRoute,
} as any)
const AppLoansIdRoute = AppLoansIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppLoansRoute,
} as any)
const AppKycSignatureRoute = AppKycSignatureRouteImport.update({
  id: '/signature',
  path: '/signature',
  getParentRoute: () => AppKycRoute,
} as any)
const AppKycNomineeRoute = AppKycNomineeRouteImport.update({
  id: '/nominee',
  path: '/nominee',
  getParentRoute: () => AppKycRoute,
} as any)
const AppKycMandatoryRoute = AppKycMandatoryRouteImport.update({
  id: '/mandatory',
  path: '/mandatory',
  getParentRoute: () => AppKycRoute,
} as any)
const AppKycBasicInfoRoute = AppKycBasicInfoRouteImport.update({
  id: '/basic-info',
  path: '/basic-info',
  getParentRoute: () => AppKycRoute,
} as any)
const AppLoansIdSuccessRoute = AppLoansIdSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => AppLoansIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/kyc': typeof AppKycRouteWithChildren
  '/app/loans': typeof AppLoansRouteWithChildren
  '/app/notifications': typeof AppNotificationsRoute
  '/app/passbook': typeof AppPassbookRoute
  '/app/kyc/basic-info': typeof AppKycBasicInfoRoute
  '/app/kyc/mandatory': typeof AppKycMandatoryRoute
  '/app/kyc/nominee': typeof AppKycNomineeRoute
  '/app/kyc/signature': typeof AppKycSignatureRoute
  '/app/loans/$id': typeof AppLoansIdRouteWithChildren
  '/app/loans/new': typeof AppLoansNewRoute
  '/app/loans/$id/success': typeof AppLoansIdSuccessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/kyc': typeof AppKycRouteWithChildren
  '/app/loans': typeof AppLoansRouteWithChildren
  '/app/notifications': typeof AppNotificationsRoute
  '/app/passbook': typeof AppPassbookRoute
  '/app/kyc/basic-info': typeof AppKycBasicInfoRoute
  '/app/kyc/mandatory': typeof AppKycMandatoryRoute
  '/app/kyc/nominee': typeof AppKycNomineeRoute
  '/app/kyc/signature': typeof AppKycSignatureRoute
  '/app/loans/$id': typeof AppLoansIdRouteWithChildren
  '/app/loans/new': typeof AppLoansNewRoute
  '/app/loans/$id/success': typeof AppLoansIdSuccessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/kyc': typeof AppKycRouteWithChildren
  '/app/loans': typeof AppLoansRouteWithChildren
  '/app/notifications': typeof AppNotificationsRoute
  '/app/passbook': typeof AppPassbookRoute
  '/app/kyc/basic-info': typeof AppKycBasicInfoRoute
  '/app/kyc/mandatory': typeof AppKycMandatoryRoute
  '/app/kyc/nominee': typeof AppKycNomineeRoute
  '/app/kyc/signature': typeof AppKycSignatureRoute
  '/app/loans/$id': typeof AppLoansIdRouteWithChildren
  '/app/loans/new': typeof AppLoansNewRoute
  '/app/loans/$id/success': typeof AppLoansIdSuccessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/register'
    | '/app/dashboard'
    | '/app/kyc'
    | '/app/loans'
    | '/app/notifications'
    | '/app/passbook'
    | '/app/kyc/basic-info'
    | '/app/kyc/mandatory'
    | '/app/kyc/nominee'
    | '/app/kyc/signature'
    | '/app/loans/$id'
    | '/app/loans/new'
    | '/app/loans/$id/success'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/login'
    | '/register'
    | '/app/dashboard'
    | '/app/kyc'
    | '/app/loans'
    | '/app/notifications'
    | '/app/passbook'
    | '/app/kyc/basic-info'
    | '/app/kyc/mandatory'
    | '/app/kyc/nominee'
    | '/app/kyc/signature'
    | '/app/loans/$id'
    | '/app/loans/new'
    | '/app/loans/$id/success'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/register'
    | '/app/dashboard'
    | '/app/kyc'
    | '/app/loans'
    | '/app/notifications'
    | '/app/passbook'
    | '/app/kyc/basic-info'
    | '/app/kyc/mandatory'
    | '/app/kyc/nominee'
    | '/app/kyc/signature'
    | '/app/loans/$id'
    | '/app/loans/new'
    | '/app/loans/$id/success'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/passbook': {
      id: '/app/passbook'
      path: '/passbook'
      fullPath: '/app/passbook'
      preLoaderRoute: typeof AppPassbookRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/loans': {
      id: '/app/loans'
      path: '/loans'
      fullPath: '/app/loans'
      preLoaderRoute: typeof AppLoansRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/kyc': {
      id: '/app/kyc'
      path: '/kyc'
      fullPath: '/app/kyc'
      preLoaderRoute: typeof AppKycRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/loans/new': {
      id: '/app/loans/new'
      path: '/new'
      fullPath: '/app/loans/new'
      preLoaderRoute: typeof AppLoansNewRouteImport
      parentRoute: typeof AppLoansRoute
    }
    '/app/loans/$id': {
      id: '/app/loans/$id'
      path: '/$id'
      fullPath: '/app/loans/$id'
      preLoaderRoute: typeof AppLoansIdRouteImport
      parentRoute: typeof AppLoansRoute
    }
    '/app/kyc/signature': {
      id: '/app/kyc/signature'
      path: '/signature'
      fullPath: '/app/kyc/signature'
      preLoaderRoute: typeof AppKycSignatureRouteImport
      parentRoute: typeof AppKycRoute
    }
    '/app/kyc/nominee': {
      id: '/app/kyc/nominee'
      path: '/nominee'
      fullPath: '/app/kyc/nominee'
      preLoaderRoute: typeof AppKycNomineeRouteImport
      parentRoute: typeof AppKycRoute
    }
    '/app/kyc/mandatory': {
      id: '/app/kyc/mandatory'
      path: '/mandatory'
      fullPath: '/app/kyc/mandatory'
      preLoaderRoute: typeof AppKycMandatoryRouteImport
      parentRoute: typeof AppKycRoute
    }
    '/app/kyc/basic-info': {
      id: '/app/kyc/basic-info'
      path: '/basic-info'
      fullPath: '/app/kyc/basic-info'
      preLoaderRoute: typeof AppKycBasicInfoRouteImport
      parentRoute: typeof AppKycRoute
    }
    '/app/loans/$id/success': {
      id: '/app/loans/$id/success'
      path: '/success'
      fullPath: '/app/loans/$id/success'
      preLoaderRoute: typeof AppLoansIdSuccessRouteImport
      parentRoute: typeof AppLoansIdRoute
    }
  }
}

interface AppKycRouteChildren {
  AppKycBasicInfoRoute: typeof AppKycBasicInfoRoute
  AppKycMandatoryRoute: typeof AppKycMandatoryRoute
  AppKycNomineeRoute: typeof AppKycNomineeRoute
  AppKycSignatureRoute: typeof AppKycSignatureRoute
}

const AppKycRouteChildren: AppKycRouteChildren = {
  AppKycBasicInfoRoute: AppKycBasicInfoRoute,
  AppKycMandatoryRoute: AppKycMandatoryRoute,
  AppKycNomineeRoute: AppKycNomineeRoute,
  AppKycSignatureRoute: AppKycSignatureRoute,
}

const AppKycRouteWithChildren =
  AppKycRoute._addFileChildren(AppKycRouteChildren)

interface AppLoansIdRouteChildren {
  AppLoansIdSuccessRoute: typeof AppLoansIdSuccessRoute
}

const AppLoansIdRouteChildren: AppLoansIdRouteChildren = {
  AppLoansIdSuccessRoute: AppLoansIdSuccessRoute,
}

const AppLoansIdRouteWithChildren = AppLoansIdRoute._addFileChildren(
  AppLoansIdRouteChildren,
)

interface AppLoansRouteChildren {
  AppLoansIdRoute: typeof AppLoansIdRouteWithChildren
  AppLoansNewRoute: typeof AppLoansNewRoute
}

const AppLoansRouteChildren: AppLoansRouteChildren = {
  AppLoansIdRoute: AppLoansIdRouteWithChildren,
  AppLoansNewRoute: AppLoansNewRoute,
}

const AppLoansRouteWithChildren = AppLoansRoute._addFileChildren(
  AppLoansRouteChildren,
)

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppKycRoute: typeof AppKycRouteWithChildren
  AppLoansRoute: typeof AppLoansRouteWithChildren
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPassbookRoute: typeof AppPassbookRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppKycRoute: AppKycRouteWithChildren,
  AppLoansRoute: AppLoansRouteWithChildren,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPassbookRoute: AppPassbookRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
